name: EnderdragonsPlus
main: de.tobiyas.enderdragonsplus.EnderdragonsPlus
version: 1.12.2_Jeppa
website: http://dev.bukkit.org/server-mods/enderdragonsplus/
author: tobiyas
fixes: Jeppa
depend:
softdepend: [DragonTravel,Vault]

description: >
             plugin to handle Enderdragons better
commands:
  enderdragonsplus:
    descroption: gives help for the Plugin
    aliases: [edp,edphelp,edph]
    usage: |
           /edp
  killenderdragons:
    description: Kills all dragons in range (if range = 0, kills ALL dragons. Default is 100)
    aliases: [kedp]
    usage: |
           /killenderdragons [range]
  spawnenderdragon:
    description: spawns a new LimitedEnderDragon to your position
    aliases: [sedp]
    usage: |
           /spawnenderdragon [AgeName]
  edpreload:
    description: reloads the config of Enderdragons+
    aliases: [edprc]
    usage: |
           /edpreload
  edpgohome:
    description: sends all LimitedEnderDragons to their home
    aliases: [edpgh]
    usage: |
           /edpgohome
  edpinfo:
    description: info loaded
    aliases: []
    usage: |
           /edpinfo
  edprespawner:
    description: creates a dragon respawner
    aliases: []
    usage: |
           /epdrespawner create <spawnerName> [dragonAgeName] [respawntime] [maxDragons]
  edpride:
    description: creates a dragon to ride
    aliases: [edpr]
    usage: |
           /edpr
  edplag:
    description: checks how much time the Plugin took for lag.
    aliases: []
    usage: |
           /edplag
  edpflyto:
    description: take a dragon to the coords passed
    aliases: []
    usage: |
           /edpflyto
  #edpbreath: #Disabled. Not for production code. Only for testing
  #  description: fires a breath in your sight direction.
  #  aliases: [edpb]
  #  usage: |
  #         /edpbreath